### ISSUE TITLE
No text visible / 沒有文字可見

### ISSUE THREAD

**Issue by epigraphe** [manier13579/GABS-AddressBookSystem#7]
Good day. I installed the script, but after logging in I do not see any text in the menu. Google Chrome shows an error. I believe that the text is not visible because of it. Screenshot attached. Help me please.

--

我在翻譯的幫助下翻譯了它。
沒有文字可見
下午好 我安裝了腳本，但登錄後我在菜單中看不到任何文字。 谷歌瀏覽器顯示錯誤。 我認為由於這個原因，文字不可見。 我附上截圖。 請幫助。

![image](https://user-images.githubusercontent.com/6083395/59174821-a94a1480-8b5b-11e9-86cf-89c540b28b6e.png)

**Comment by manier13579** [comment]
I think this is because the data of the txl_yuyan table in your database is not imported properly. Please confirm if there is data in the table named txl_yuyan. Re-import the db.sql file if it has no data

If this is not the case, please provide the server return information, view method: Google Developer Tools -> network -> request (name: lang_controller.php) -> response

**Comment by epigraphe** [comment]
The table was not empty, I once again imported the values - nothing has changed.

lang_controller.php returns null

![image](https://user-images.githubusercontent.com/6083395/59246412-f940de00-8c24-11e9-98b1-be68f259b590.png)

**Comment by epigraphe** [comment]
I took the old version of this file with $response = array(); on line 24 and it all worked
